---
- name: extract model
  shell: 'cat "{{ item }}" | jq .model'
  register: model

- name: extract title
  shell: 'cat "{{ item }}" | jq .model.title'
  register: title

- name: extract uid
  shell: 'cat "{{ item }}" | jq .model.libraryPanel.uid'
  register: uid

- name: set fact
  set_fact:
    model: "{{ model.stdout | from_json }}"
    title: "{{ title.stdout | from_json }}"
    uid: "{{ uid.stdout | from_json }}"

- name: "Define the library panel {{ title }} to Grafana"
  ansible.builtin.uri:
    url: "http://{{ groups['grafana'][0] }}:{{ grafana_port }}/api/library-elements"
    user: "{{ grafana_user }}"
    password: "{{ grafana_password }}"
    method: POST
    validate_certs: no
    force_basic_auth: yes
    body_format: json
    body: >
      {
        "model": {{ model }}, 
        "name": "{{ title }}",
        "kind": 1,
        "uid": "{{ uid }}"
      }

