---
- name: Deploy Prometheus Exporters to ceph nodes
  hosts: 
    - ceph
  gather_facts: no
  roles:
    - defaults
    - common
    - node-exporter
    - process-exporter
  tasks:
    - block:
      - name: update prometheus config
        include_tasks: roles/prometheus/tasks/build_prometheus_yml.yml

      - name: reload prometheus
        include_tasks: roles/prometheus/tasks/reload_prometheus.yml

      delegate_to: "{{ groups['prometheus'][0] }}"

- name: Deploy exporters to clients
  hosts: clients
  gather_facts: no
  roles:
    - defaults
    - common 
    - node-exporter
    
